/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/C6uTFbI4A3A
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"

export function Nsgtrack() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-background">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6 bg-card">
        <Link
          href="#"
          className="flex items-center gap-2 text-lg font-semibold sm:text-base mr-4 text-card-foreground"
          prefetch={false}
        >
          <FrameIcon className="w-6 h-6" />
          <span className="sr-only">NSG Ops</span>
        </Link>
        <nav className="hidden font-medium sm:flex flex-row items-center gap-5 text-sm lg:gap-6 text-card-foreground">
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Teams
          </Link>
          <Link href="#" className="font-bold" prefetch={false}>
            Live Tracking
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Missions
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Logs
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Settings
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <Button variant="ghost" size="icon" className="rounded-full ml-auto text-card-foreground">
            <img
              src="/placeholder.svg"
              width="32"
              height="32"
              className="rounded-full border"
              alt="Avatar"
              style={{ aspectRatio: "32/32", objectFit: "cover" }}
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] bg-muted/40 flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="max-w-6xl w-full mx-auto grid gap-2">
          <h1 className="font-semibold text-3xl text-card-foreground">Live Tracking</h1>
          <p className="text-muted-foreground">
            Monitor the real-time location of your NSG House Intervention Teams during operations.
          </p>
        </div>
        <div className="grid gap-6 max-w-6xl w-full mx-auto">
          <div className="flex flex-col md:flex-row md:items-center gap-2 md:gap-4">
            <Input type="search" placeholder="Search teams..." className="bg-card text-card-foreground" />
            <div className="flex items-center gap-4">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" className="pl-3 flex-1 bg-card text-card-foreground justify-start">
                    <CalendarClockIcon className="mr-2 h-4 w-4 shrink-0" />
                    Select Mission
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="w-auto p-0" align="end">
                  <DropdownMenuItem>Operation Thunderstorm</DropdownMenuItem>
                  <DropdownMenuItem>Operation Nighthawk</DropdownMenuItem>
                  <DropdownMenuItem>Operation Blackout</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" className="bg-card text-card-foreground">
                    Team Status <ChevronDownIcon className="ml-2 h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuCheckboxItem checked>Deployed</DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem>On Standby</DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem>Returning</DropdownMenuCheckboxItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
          <div className="border rounded-lg overflow-hidden grid gap-4 lg:gap-px lg:bg-gray-100">
            <div className="flex flex-col lg:flex-row bg-card text-sm p-2 relative">
              <div className="p-2 grid gap-1 flex-1">
                <div className="font-medium text-card-foreground">Alpha Team</div>
                <div className="text-muted-foreground">
                  Operation Thunderstorm{" "}
                  <Badge variant="outline" className="bg-card text-card-foreground">
                    Deployed
                  </Badge>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="p-2 grid gap-1 flex-1">
                <div className="flex items-start gap-2">
                  <span className="inline-flex w-3 h-3 bg-green-400 rounded-full translate-y-1" />
                  <div className="text-card-foreground">
                    Floor 3, Building A
                    <div className="text-muted-foreground">2m 35s</div>
                  </div>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="p-2 grid gap-1 flex-1">
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Sgt. John Doe</span>
                </div>
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Cpl. Jane Smith</span>
                </div>
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Pvt. Alex Johnson</span>
                </div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon" className="absolute top-4 right-4 text-card-foreground">
                    <MoveHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>View Team</DropdownMenuItem>
                  <DropdownMenuItem>Update Status</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem disabled>Recall Team</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
            <div className="flex flex-col lg:flex-row bg-card text-sm p-2 relative">
              <div className="p-2 grid gap-1 flex-1">
                <div className="font-medium text-card-foreground">Bravo Team</div>
                <div className="text-muted-foreground">
                  Operation Nighthawk{" "}
                  <Badge variant="outline" className="bg-card text-card-foreground">
                    Deployed
                  </Badge>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="p-2 grid gap-1 flex-1">
                <div className="flex items-start gap-2">
                  <span className="inline-flex w-3 h-3 bg-green-400 rounded-full translate-y-1" />
                  <div className="text-card-foreground">
                    Floor 5, Building B
                    <div className="text-muted-foreground">1m 23s</div>
                  </div>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="p-2 grid gap-1 flex-1">
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Sgt. Sarah Lee</span>
                </div>
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Cpl. Mike Chen</span>
                </div>
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Pvt. David Kim</span>
                </div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon" className="absolute top-4 right-4 text-card-foreground">
                    <MoveHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>View Team</DropdownMenuItem>
                  <DropdownMenuItem>Update Status</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem disabled>Recall Team</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
            <div className="flex flex-col lg:flex-row bg-card text-sm p-2 relative">
              <div className="p-2 grid gap-1 flex-1">
                <div className="font-medium text-card-foreground">Charlie Team</div>
                <div className="text-muted-foreground">
                  Operation Blackout{" "}
                  <Badge variant="outline" className="bg-card text-card-foreground">
                    On Standby
                  </Badge>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="p-2 grid gap-1 flex-1">
                <div className="flex items-start gap-2">
                  <span className="inline-flex w-3 h-3 bg-yellow-400 rounded-full translate-y-1" />
                  <div className="text-card-foreground">
                    Floor 2, Building C
                    <div className="text-muted-foreground">4m 22s</div>
                  </div>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="p-2 grid gap-1 flex-1">
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Sgt. Emily Patel</span>
                </div>
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Cpl. Arun Sharma</span>
                </div>
                <div className="flex items-center gap-2 text-card-foreground">
                  <MedalIcon className="w-4 h-4" />
                  <span>Pvt. Isha Gupta</span>
                </div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon" className="absolute top-4 right-4 text-card-foreground">
                    <MoveHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>View Team</DropdownMenuItem>
                  <DropdownMenuItem>Update Status</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem disabled>Recall Team</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function CalendarClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 7.5V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h3.5" />
      <path d="M16 2v4" />
      <path d="M8 2v4" />
      <path d="M3 10h5" />
      <path d="M17.5 17.5 16 16.3V14" />
      <circle cx="16" cy="16" r="6" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function FrameIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  )
}


function MedalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15" />
      <path d="M11 12 5.12 2.2" />
      <path d="m13 12 5.88-9.8" />
      <path d="M8 7h8" />
      <circle cx="12" cy="17" r="5" />
      <path d="M12 18v-2h-.5" />
    </svg>
  )
}


function MoveHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  )
}
