/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9Qom1PWucMU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Page2() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <NfcIcon className="w-8 h-8" />
          <h1 className="text-2xl font-bold">NSG CQB Tracking</h1>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost">
            <SettingsIcon className="w-6 h-6" />
          </Button>
          <Button variant="ghost">
            <HandHelpingIcon className="w-6 h-6" />
          </Button>
        </div>
      </header>
      <div className="flex-1 grid grid-cols-[1fr_2fr] gap-6 p-6">
        <div className="bg-card rounded-lg shadow-lg p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-bold">Team Members</h2>
            <Button variant="ghost">
              <RefreshCwIcon className="w-5 h-5" />
            </Button>
          </div>
          <div className="flex flex-col gap-2 overflow-auto max-h-[400px]">
            <div className="flex items-center gap-4 bg-card-foreground/10 rounded-md p-3">
              <div className="bg-red-600 w-3 h-3 rounded-full" />
              <div>
                <div className="font-medium">John Doe</div>
                <div className="text-muted-foreground text-sm">2nd Floor, Room 301</div>
              </div>
            </div>
            <div className="flex items-center gap-4 bg-card-foreground/10 rounded-md p-3">
              <div className="bg-yellow-500 w-3 h-3 rounded-full" />
              <div>
                <div className="font-medium">Jane Smith</div>
                <div className="text-muted-foreground text-sm">Basement, Room 102</div>
              </div>
            </div>
            <div className="flex items-center gap-4 bg-card-foreground/10 rounded-md p-3">
              <div className="bg-green-600 w-3 h-3 rounded-full" />
              <div>
                <div className="font-medium">Michael Johnson</div>
                <div className="text-muted-foreground text-sm">3rd Floor, Room 405</div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-card rounded-lg shadow-lg p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-bold">Building Layout</h2>
            <Button variant="ghost">
              <ZoomInIcon className="w-5 h-5" />
            </Button>
          </div>
          <div className="flex-1 relative">
            <img
              src="/placeholder.svg"
              alt="Building Layout"
              className="w-full h-full object-contain"
              width="600"
              height="400"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center">
              <div className="bg-red-600 w-5 h-5 rounded-full animate-ping" />
              <div className="bg-red-600 w-3 h-3 rounded-full" />
              <div className="bg-yellow-500 w-5 h-5 rounded-full animate-ping ml-10" />
              <div className="bg-yellow-500 w-3 h-3 rounded-full ml-10" />
              <div className="bg-green-600 w-5 h-5 rounded-full animate-ping ml-20" />
              <div className="bg-green-600 w-3 h-3 rounded-full ml-20" />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function HandHelpingIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 12h2a2 2 0 1 0 0-4h-3c-.6 0-1.1.2-1.4.6L3 14" />
      <path d="m7 18 1.6-1.4c.3-.4.8-.6 1.4-.6h4c1.1 0 2.1-.4 2.8-1.2l4.6-4.4a2 2 0 0 0-2.75-2.91l-4.2 3.9" />
      <path d="m2 13 6 6" />
    </svg>
  )
}


function NfcIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8.32a7.43 7.43 0 0 1 0 7.36" />
      <path d="M9.46 6.21a11.76 11.76 0 0 1 0 11.58" />
      <path d="M12.91 4.1a15.91 15.91 0 0 1 .01 15.8" />
      <path d="M16.37 2a20.16 20.16 0 0 1 0 20" />
    </svg>
  )
}


function RefreshCwIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function ZoomInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <line x1="21" x2="16.65" y1="21" y2="16.65" />
      <line x1="11" x2="11" y1="8" y2="14" />
      <line x1="8" x2="14" y1="11" y2="11" />
    </svg>
  )
}
